### ISSUE TITLE
How do I return a 404? or any other status message 

### ISSUE THREAD

**Issue by NullVoxPopuli** [joukevandermaas/saule#90] opened 2016-04-13 15:18 UTC

**Comment by joukevandermaas** [comment] 2016-04-13 21:48
The same way you would in a 'regular' ASP.Net project. That should still 'just work'. Can you provide some examples of what you tried and what you would have expected to happen?

**Comment by NullVoxPopuli** [comment] 2016-04-13 21:51
Doesn't the return type of the controller action have to match the resource's underlying type?
How would I return a response that wasn't that type?

**Comment by joukevandermaas** [comment] 2016-04-14 07:16
If you return `HttpResponseMessage`, you can do:

```csharp
return Request.CreateResponse(HttpStatusCode.NotFound, new CustomException("My message"));
```

Which will do the right thing.

See [the ASP.Net](http://www.asp.net/web-api/overview/error-handling/exception-handling#httperror) documentation.

**Comment by NullVoxPopuli** [comment] 2016-04-14 11:55
I don't think this works, cause it appears Saule is intercepting the response handling. :-\
this is what I tired:
```csharp
       [HttpPost]
        [ReturnsResource(typeof (EngineResource))]
        [Route("engines/")]
        public object Create([FromBody] JObject engineData)
        {
            try
            {
                var engine = CurrentUser.Engines.Create(engineData);
                return engine;
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                var errorHandler = new DbEntityValidationExceptionHandler(ex);
                var obj = errorHandler.AsErrors();
                // TODO: no 422?
                var response = Request.CreateResponse(HttpStatusCode.BadRequest, obj);
                return response;
            }
        }
```

**Comment by joukevandermaas** [comment] 2016-04-14 14:25
Saule only supports serializing exceptions as errors; if your `errorHandler.AsErrors` call returns something else, it will not work. Maybe you can wrap it in custom exception?

**Comment by joukevandermaas** [comment] 2016-06-03 20:06
I'm closing this. Feel free to re-open if the issue is not clear or resolved.

**Closed by joukevandermaas** 2016-06-03 20:06 UTC
Labels: question
