### ISSUE TITLE
Upload a file and return json api

### ISSUE THREAD

**Issue by joanmarcfeina** [joukevandermaas/saule#171] opened 2017-08-30 06:41 UTC
Hello!

I have been working with Saule library for some months succesfully but now I need to upload a file for processing and then return some data. 
At first I did an endpoint and from postman I upload the file and some additional data with Content-Type: multipart/form-data header. The request reaches the endpoint and after a couple of seconds I get the json response.

Now I need the same but I need the json response to follow the json standards with relationships, links and so on.
Here's the code I am using:
`       

        [Route("booo/")]
        [ReturnsResource(typeof(BooResource))]
        [HttpPost]
        public async Task<IHttpActionResult> FooFunction()
        {
           ...
           return Content(status, FooResult);
        }`

The problem I am facing is that if I make a post request with Content-Type: multipart/form-data I get an "415 unsupported media type" but if I change the content-type to application/vnd.api+json I can't read the file.

What can I do?

Thank you!

**Comment by joukevandermaas** [comment] 2017-08-30 07:58
This seems like a duplicate of #167. Can you try the latest pre-release and see if that resolves your problem?

**Comment by joanmarcfeina** [comment] 2017-08-30 09:16
I tried the #167 with the latest Nuget version and it didn't work. You mean try the #167 with the pre-release?

**Comment by joukevandermaas** [comment] 2017-08-30 11:59
I mean version `1.7.0.444-beta` on nuget. I think #167 was fixed in #168, in the sense that you can now add the JSON API formatter to the *end* of the collection, so the regular `multipart/form-data` one gets a chance to run first.

**Closed** 2017-10-16 12:47 UTC
